spring.application.name=veterinaria-gran-malo
server.port=8080
server.servlet.session.timeout=30m
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xepdb1
spring.datasource.username=Veterinaria
spring.datasource.password=6493
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=10m

app.rabbit.exchange=veterinaria.eventos
app.rabbit.queue=veterinaria.operaciones
app.rabbit.routing-key=operacion.registrada
