
CREATE TABLE ADOPCION (
    Adopcion_Id      NUMBER(10) NOT NULL,
    Fecha_Adopcion   DATE,
    Condiciones      VARCHAR2(100),
    Estado_Adopcion  VARCHAR2(50) CHECK (Estado_Adopcion IN ('Pendiente', 'En Revision', 'Aprobada', 'Rechazada', 'Finalizada')),
    Animal_Id        NUMBER(10),
    Cliente_Id       NUMBER(10),
    Empleado_Id      NUMBER(10)
);

CREATE TABLE ANIMAL (
    Animal_Id        NUMBER(10) NOT NULL,
    Nombre_Animal    VARCHAR2(50),
    Fecha_Nacimiento DATE,
    Genero           VARCHAR2(50),
    Color            VARCHAR2(50),
    Precio_Lista     NUMBER(10, 2) CHECK (Precio_Lista >= 0),
    Raza_Id          NUMBER(10),
    Cliente_Id       NUMBER(10),
    Estado_Animal    VARCHAR2(50) CHECK (Estado_Animal IN ('Disponible', 'Con Dueño', 'En Adopcion', 'Adoptado', 'Hospitalizado', 'En tratamiento', 'Fallecido', 'Reservado')),
    Proveedor_Id     NUMBER(10)
);

CREATE TABLE CATEGORIA_ANIMALES (
    CategoriaA_Id           NUMBER(10) NOT NULL,
    Nombre_Categoria_Animal VARCHAR2(100)
);

CREATE TABLE CATEGORIA_PRODUCTO (
    CategoriaP_Id                 NUMBER(10) NOT NULL,
    Nombre_Categoria_Producto     VARCHAR2(50),
    Descripcion_Categoria_Producto VARCHAR2(100)
);

CREATE TABLE CIRUGIA (
    Cirugia_Id     NUMBER(10) NOT NULL,
    Fecha          DATE,
    Tipo_Cirugia   VARCHAR2(50),
    Descripcion    VARCHAR2(100),
    Animal_Id      NUMBER(10),
    Empleado_Id    NUMBER(10),
    Venta_Id       NUMBER(10),
    Costo_Cirugia NUMBER(10, 2) CHECK (Costo_Cirugia >= 0)
);

CREATE TABLE CLIENTE (
    Cliente_Id     NUMBER(10) NOT NULL,
    Nombre_Cliente VARCHAR2(50),
    Direccion      VARCHAR2(100),
    Ciudad         VARCHAR2(50),
    Estado         VARCHAR2(50),
    CP             VARCHAR2(10),
    Telefono       VARCHAR2(15),
    Email          VARCHAR2(100),
    Fecha_Registro DATE
);

CREATE TABLE CONSULTA (
    Consulta_Id   NUMBER(10) NOT NULL,
    Fecha         DATE,
    Motivo        VARCHAR2(100),
    Diagnostico   VARCHAR2(100),
    Tratamiento   VARCHAR2(100),
    Empleado_Id   NUMBER(10),
    Animal_Id     NUMBER(10),
    Venta_Id      NUMBER(10),
    Costo_Consulta NUMBER(10, 2) CHECK (Costo_Consulta >= 0)
);

CREATE TABLE DETALLE_PEDIDO_ANIMAL (
    Animal_Id   NUMBER(10) NOT NULL,
    PedidoA_Id  NUMBER(10) NOT NULL,
    Costo       NUMBER(10, 2) CHECK (Costo >= 0)
);

CREATE TABLE DETALLE_PEDIDO_PRODUCTO (
    PedidoP_Id  NUMBER(10) NOT NULL,
    Producto_Id NUMBER(10) NOT NULL,
    Cantidad    NUMBER(10) CHECK (Cantidad >= 0),
    Costo       NUMBER(10, 2) CHECK (Costo >= 0)
);

CREATE TABLE EMPLEADO (
    Empleado_Id      NUMBER(10) NOT NULL,
    Nombre_Empleado  VARCHAR2(50),
    Telefono         VARCHAR2(15),
    Fecha_Ingreso    DATE,
    Puesto           VARCHAR2(50),
    Especialidad     VARCHAR2(50),
    Salario          NUMBER(10,2),
    Fecha_Nacimiento DATE,
    RFC              VARCHAR2(13) UNIQUE
);

CREATE TABLE HISTORIAL_MEDICO (
    Historial_Id NUMBER(10) NOT NULL,
    Fecha        DATE,
    Notas        VARCHAR2(100),
    Tipo         VARCHAR2(50),
    Animal_Id    NUMBER(10),
    Empleado_Id  NUMBER(10),
    Descripcion  VARCHAR2(100),
    Peso         NUMBER(10, 2) CHECK (Peso >= 0),
    Temperatura  NUMBER(10, 2) CHECK (Temperatura >= 0)
);

CREATE TABLE PEDIDO_ANIMAL (
    PedidoA_Id           NUMBER(10) NOT NULL,
    Fecha_Orden          DATE,
    Fecha_Recepcion      DATE,
    Costo_Envio          NUMBER(10, 2) CHECK (Costo_Envio >= 0),
    Empleado_Id          NUMBER(10),
    Proveedor_Id         NUMBER(10),
    Tipo                 VARCHAR2(100),
    Estado_Pedido_Animal VARCHAR2(50) CHECK (Estado_Pedido_Animal IN ('Solicitado', 'Entregado', 'Reparto', 'Enviado'))
);

CREATE TABLE PEDIDO_PRODUCTO (
    PedidoP_Id              NUMBER(10) NOT NULL,
    Fecha_Orden             DATE,
    Fecha_Recepcion         DATE,
    Costo_Envio             NUMBER(10, 2) CHECK (Costo_Envio >= 0),
    Empleado_Id             NUMBER(10),
    Proveedor_Id            NUMBER(10),
    Tipo                    VARCHAR2(100),
    Estado_Pedido_Producto  VARCHAR2(50) CHECK (Estado_Pedido_Producto IN ('Solicitado', 'Entregado', 'Reparto', 'Enviado'))
);

CREATE TABLE PRODUCTOS (
    Producto_Id          NUMBER(10) NOT NULL,
    Descripcion_Producto VARCHAR2(100),
    Precio_Lista         NUMBER (10, 2) CHECK (Precio_Lista >= 0),
    Existencia           NUMBER (10) CHECK (Existencia >= 0),
    Requiere_Receta      VARCHAR2(2) CHECK (Requiere_Receta IN ('S', 'N')),
    CategoriaP_Id        NUMBER (10)
);

CREATE TABLE PROVEEDOR (
    Proveedor_Id     NUMBER(10) NOT NULL,
    Nombre           VARCHAR2(50),
    Contacto         VARCHAR2(50),
    Telefono         NUMBER (15),
    Direccion        VARCHAR2(50),
    Ciudad           VARCHAR2(50),
    Estado_Proveedor VARCHAR2(50) CHECK (Estado_Proveedor IN ('Activo', 'Inactivo', 'Suspendido')),
    CP               VARCHAR2(10)
);

CREATE TABLE RAZA (
    Raza_Id       NUMBER(10) NOT NULL,
    CategoriaA_Id NUMBER(10),
    Nombre_Raza   VARCHAR2(50),
    CONSTRAINT UK_RAZA_NOMBRE UNIQUE (CategoriaA_Id, Nombre_Raza)
);

CREATE TABLE VENTAS (
    Venta_Id     NUMBER(10) NOT NULL,
    Fecha        DATE,
    Cliente_Id   NUMBER(10),
    Empleado_Id  NUMBER(10),
    Metodo_Pago  VARCHAR2(50) CHECK (Metodo_Pago IN ('Efectivo', 'Tarjeta', 'Mixto')),
    Tipo_Ventas  VARCHAR2(100)
);

CREATE TABLE VENTAS_ANIMAL (
    Animal_Id    NUMBER(10) NOT NULL,
    Venta_Id     NUMBER(10) NOT NULL,
    Precio_Venta NUMBER(10, 2) CHECK (Precio_Venta >= 0)
);

CREATE TABLE VENTAS_PRODUCTO (
    Venta_Id     NUMBER(10) NOT NULL,
    Producto_Id  NUMBER(10) NOT NULL,
    Precio_Venta NUMBER(10, 2) CHECK (Precio_Venta >= 0),
    Cantidad     NUMBER(10) CHECK (Cantidad >= 0)
);

ALTER TABLE ADOPCION ADD CONSTRAINT PK_ADOPCION PRIMARY KEY (Adopcion_Id);
ALTER TABLE ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY (Animal_Id);
ALTER TABLE CATEGORIA_ANIMALES ADD CONSTRAINT PK_CATEGORIA_ANIMALES PRIMARY KEY (CategoriaA_Id);
ALTER TABLE CATEGORIA_PRODUCTO ADD CONSTRAINT PK_CATEGORIA_PRODUCTO PRIMARY KEY (CategoriaP_Id);
ALTER TABLE CIRUGIA ADD CONSTRAINT PK_CIRUGIA PRIMARY KEY (Cirugia_Id);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (Cliente_Id);
ALTER TABLE CONSULTA ADD CONSTRAINT PK_CONSULTA PRIMARY KEY (Consulta_Id);
ALTER TABLE DETALLE_PEDIDO_ANIMAL ADD CONSTRAINT PK_DETALLE_PEDIDO_ANIMAL PRIMARY KEY (Animal_Id, PedidoA_Id);
ALTER TABLE DETALLE_PEDIDO_PRODUCTO ADD CONSTRAINT PK_DETALLE_PEDIDO_PRODUCTO PRIMARY KEY (PedidoP_Id, Producto_Id);
ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (Empleado_Id);
ALTER TABLE HISTORIAL_MEDICO ADD CONSTRAINT PK_HISTORIAL_MEDICO PRIMARY KEY (Historial_Id);
ALTER TABLE PEDIDO_ANIMAL ADD CONSTRAINT PK_PEDIDO_ANIMAL PRIMARY KEY (PedidoA_Id);
ALTER TABLE PEDIDO_PRODUCTO ADD CONSTRAINT PK_PEDIDO_PRODUCTO PRIMARY KEY (PedidoP_Id);
ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (Producto_Id);
ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (Proveedor_Id);
ALTER TABLE RAZA ADD CONSTRAINT PK_RAZA PRIMARY KEY (Raza_Id);
ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (Venta_Id);
ALTER TABLE VENTAS_ANIMAL ADD CONSTRAINT PK_VENTAS_ANIMAL PRIMARY KEY (Animal_Id, Venta_Id);
ALTER TABLE VENTAS_PRODUCTO ADD CONSTRAINT PK_VENTAS_PRODUCTO PRIMARY KEY (Venta_Id, Producto_Id);


ALTER TABLE ADOPCION ADD CONSTRAINT FK_ADOPCION_ANIMAL FOREIGN KEY (Animal_Id) REFERENCES ANIMAL(Animal_Id) ON DELETE SET NULL;
ALTER TABLE ADOPCION ADD CONSTRAINT FK_ADOPCION_CLIENTE FOREIGN KEY (Cliente_Id) REFERENCES CLIENTE(Cliente_Id) ON DELETE SET NULL;
ALTER TABLE ADOPCION ADD CONSTRAINT FK_ADOPCION_EMPLEADO FOREIGN KEY (Empleado_Id) REFERENCES EMPLEADO(Empleado_Id) ON DELETE SET NULL;

ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL_RAZA FOREIGN KEY (Raza_Id) REFERENCES RAZA(Raza_Id) ON DELETE SET NULL;
ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL_CLIENTE FOREIGN KEY (Cliente_Id) REFERENCES CLIENTE(Cliente_Id) ON DELETE SET NULL;
ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL_PROVEEDOR FOREIGN KEY (Proveedor_Id) REFERENCES PROVEEDOR(Proveedor_Id) ON DELETE SET NULL;

ALTER TABLE CIRUGIA ADD CONSTRAINT FK_CIRUGIA_ANIMAL FOREIGN KEY (Animal_Id) REFERENCES ANIMAL(Animal_Id) ON DELETE SET NULL;
ALTER TABLE CIRUGIA ADD CONSTRAINT FK_CIRUGIA_EMPLEADO FOREIGN KEY (Empleado_Id) REFERENCES EMPLEADO(Empleado_Id) ON DELETE SET NULL;
ALTER TABLE CIRUGIA ADD CONSTRAINT FK_CIRUGIA_VENTA FOREIGN KEY (Venta_Id) REFERENCES VENTAS(Venta_Id) ON DELETE SET NULL;

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_EMPLEADO FOREIGN KEY (Empleado_Id) REFERENCES EMPLEADO(Empleado_Id) ON DELETE SET NULL;
ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_ANIMAL FOREIGN KEY (Animal_Id) REFERENCES ANIMAL(Animal_Id) ON DELETE SET NULL;
ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_VENTA FOREIGN KEY (Venta_Id) REFERENCES VENTAS(Venta_Id) ON DELETE SET NULL;

ALTER TABLE DETALLE_PEDIDO_ANIMAL ADD CONSTRAINT FK_DPA_ANIMAL FOREIGN KEY (Animal_Id) REFERENCES ANIMAL(Animal_Id);
ALTER TABLE DETALLE_PEDIDO_ANIMAL ADD CONSTRAINT FK_DPA_PEDIDO_ANIMAL FOREIGN KEY (PedidoA_Id) REFERENCES PEDIDO_ANIMAL(PedidoA_Id);

ALTER TABLE DETALLE_PEDIDO_PRODUCTO ADD CONSTRAINT FK_DPP_PEDIDO_PRODUCTO FOREIGN KEY (PedidoP_Id) REFERENCES PEDIDO_PRODUCTO(PedidoP_Id);
ALTER TABLE DETALLE_PEDIDO_PRODUCTO ADD CONSTRAINT FK_DPP_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES PRODUCTOS(Producto_Id);

ALTER TABLE HISTORIAL_MEDICO ADD CONSTRAINT FK_HM_ANIMAL FOREIGN KEY (Animal_Id) REFERENCES ANIMAL(Animal_Id) ON DELETE SET NULL;
ALTER TABLE HISTORIAL_MEDICO ADD CONSTRAINT FK_HM_EMPLEADO FOREIGN KEY (Empleado_Id) REFERENCES EMPLEADO(Empleado_Id) ON DELETE SET NULL;

ALTER TABLE PEDIDO_ANIMAL ADD CONSTRAINT FK_PA_EMPLEADO FOREIGN KEY (Empleado_Id) REFERENCES EMPLEADO(Empleado_Id) ON DELETE SET NULL;
ALTER TABLE PEDIDO_ANIMAL ADD CONSTRAINT FK_PA_PROVEEDOR FOREIGN KEY (Proveedor_Id) REFERENCES PROVEEDOR(Proveedor_Id) ON DELETE SET NULL;

ALTER TABLE PEDIDO_PRODUCTO ADD CONSTRAINT FK_PP_EMPLEADO FOREIGN KEY (Empleado_Id) REFERENCES EMPLEADO(Empleado_Id) ON DELETE SET NULL;
ALTER TABLE PEDIDO_PRODUCTO ADD CONSTRAINT FK_PP_PROVEEDOR FOREIGN KEY (Proveedor_Id) REFERENCES PROVEEDOR(Proveedor_Id) ON DELETE SET NULL;

ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN KEY (CategoriaP_Id) REFERENCES CATEGORIA_PRODUCTO(CategoriaP_Id) ON DELETE SET NULL;

ALTER TABLE RAZA ADD CONSTRAINT FK_RAZA_CATEGORIA FOREIGN KEY (CategoriaA_Id) REFERENCES CATEGORIA_ANIMALES(CategoriaA_Id) ON DELETE SET NULL;

ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_CLIENTE FOREIGN KEY (Cliente_Id) REFERENCES CLIENTE(Cliente_Id) ON DELETE SET NULL;
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_EMPLEADO FOREIGN KEY (Empleado_Id) REFERENCES EMPLEADO(Empleado_Id) ON DELETE SET NULL;

ALTER TABLE VENTAS_ANIMAL ADD CONSTRAINT FK_VA_ANIMAL FOREIGN KEY (Animal_Id) REFERENCES ANIMAL(Animal_Id);
ALTER TABLE VENTAS_ANIMAL ADD CONSTRAINT FK_VA_VENTA FOREIGN KEY (Venta_Id) REFERENCES VENTAS(Venta_Id);

ALTER TABLE VENTAS_PRODUCTO ADD CONSTRAINT FK_VP_VENTA FOREIGN KEY (Venta_Id) REFERENCES VENTAS(Venta_Id);
ALTER TABLE VENTAS_PRODUCTO ADD CONSTRAINT FK_VP_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES PRODUCTOS(Producto_Id);

COMMIT;