@echo off
set "BASE=%~dp0.."
for %%I in ("%BASE%") do set "BASE=%%~fI"
set "ERLANG_HOME=%BASE%\tools\erl-27"
set "PATH=%ERLANG_HOME%\bin;%ERLANG_HOME%\erts-15.2.7.8\bin;%PATH%"
set "RABBITMQ_BASE=%BASE%\runtime\rabbitmq431"
set "RABBITMQ_NODENAME=rabbit@localhost"
set "USERPROFILE=%RABBITMQ_BASE%"
set "HOMEDRIVE=C:"
set "HOMEPATH=%RABBITMQ_BASE:~2%"
if not exist "%RABBITMQ_BASE%" mkdir "%RABBITMQ_BASE%"
"%BASE%\tools\rabbitmq_server-4.3.1\sbin\rabbitmq-server.bat"
